name: recall
description: "Amazingly Awesome and redisgned Clipbaord Manager in Flutter."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  yaru: ^6.0.0
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.3.4
  url_launcher: ^6.3.1
  clipboard: ^0.1.3
  window_manager: ^0.4.3
  hotkey_manager: ^0.2.3
  emoji_picker_flutter: ^4.2.0
  path_provider: ^2.1.5
  sqflite: ^2.4.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
